### ISSUE TITLE
Dear shoaibilyas,  i am using facebook graph api, i would like to add post on a public page. without like that page is it possible , if possible kindly help

### ISSUE THREAD

**Issue by itekkdeveloper** [sohaibilyas/facebook-php-sdk-v5#6]

**Comment by sohaibilyas** [comment]
Please clear this to me either you want to post on a public page or you want to post a public page without liking that page?

- If you want to post on a public page and admin has blocked that access that you won't be able to do that.
- If you want to post as a page then I've made a video on that how to post as page just YouTube that even if you have not liked that page with your personal account you will be able to post as page using page access token.

**Comment by itekkdeveloper** [comment]
Thanks for reading my mail,

i would like to post multiple images to  my own page.

**Comment by sohaibilyas** [comment]
First you need to learn how to get page access token learn by watching this video https://www.youtube.com/watch?v=c4GDuYZ0Y6U then you need to watch the video I mentioned in the last comment that's about posting multiple images on a user profile but you can do the same with page using page access token, after doing so must update me here I'd love to know how did it do!

**Comment by akhilrajrsahithi** [comment]
Dear sohaibilyas,
while  I trying to post a link to my wall  with using your code _post-on-user-timeline.php_ , 
I got this  SDK ERROR:
**Facebook SDK returned an error: Unable to convert response from Graph to a GraphEdge because the response does not look like a GraphEdge. Try using GraphNodeFactory::makeGraphNode() instead**.
what should I change in my code , to post on my timeline ?
